workflow:
  title: 'Review Statement of Investment Principles'
  alias: rsoip
  sort: 1
  enabled: true
  roles:
    - client
    - lgim
    - advisory
    - specialAdvisory
    - X
  steps:
    formDataStep1:
      roles:
        - client
        - lgim
      title: 'Input return target'
      showRejectedData: true 
      initialDataConfig:
        - key: 'assetValue'
          from: scheme
          alias: 'assetValue2'
        - key: 'fundValue'
          from: scheme
          alias: 'fundValue1'          
        - from: workflowData
          workflow: key
          stepKey: key
          alias: 'returnTargetFormData2'
      # save step data to scheme dataset
      # if only mandate: true provided , step data will be fatten and saved to scheme
      mandate: true
        - from: 'tab.valueAbc'
          to: 'valueAbc'             
      stepActions:    
        STEP_ACTION_UPDATE_WORKFLOW:
          stepFunction: 'adhocDocGen'
          notificationConfig:
            notificationCode: N-R-11
              data:
                - key: PROPOSAL_NAME
                  path: 'dataset.formData.assets.proposalName'
          auditTrail:
            auditTrailAction: ATA_REQUEST_INITIAL_PROPOSAL
              data:
                - key: PROPOSAL_NAME
                  path: 'dataset.formData.assets.proposalName'
      claimConfig:                      
        - assigneeClaim: CLM-12
      globalVariables:
        - key: proposalName
          globalVariableAlias: propName
          value: 'ABC'        
    approveRejectStep2:
      title: 'Review Statement of Investment Principles'
      roles:
        - LGIM      
      authConfig:
        approvalType: 
          - LGIM
          - SELECTED
        approveCount: 3
        rejectCount: ALL
      stepActions:  
        STEP_ACTION_AUTHORIZE:
          notificationConfig:
            notificationCode: N-R-11
              data:
                - key: PROPOSAL_NAME
                  path: 'dataset.formData.assets.proposalName'
          auditTrail:
            auditTrailAction: ATA_REQUEST_INITIAL_PROPOSAL
              data:
                - key: PROPOSAL_NAME
                  path: 'dataset.formData.assets.proposalName'
      claimConfig:                      
        - assigneeClaim: CLM-12
        - authClaim: CLM-11                 
    formDataStep1:
      roles:
        - CLIENT
        - LGIM
      title: 'Input return target'
      showRejectedData: true        
    mandatestepkey:
      title: 'Review Statement of Investment Principles'
      roles:
        - LGIM
      mandateStep: true        
      assigneeClaim: CLM-12   