workflowKey:
  title: 'Workflow Title'
  sort: 1
  enabled: true
  roles:
    - CLIENT
    - LGIM
    - ADVISORY
    - SPECIAL_ADVISORY
  steps:
    step1: # form step & also the initial step of the workflow
      roles:
        - CLIENT
        - LGIM
      title: 'Step1 Title'
      claimConfig:
        assigneeClaim: CLM-1       
      preserve: true           
    step2: # Approve Reject step
      title: 'Step2 Title'
      roles:
        - LGIM
      authConfig:
        approvalType:
          - LGIM
        approveCount: 2
        rejectCount: ALL                       
      claimConfig:
        authClaim: CLM-2 
        assigneeClaim: CLM-3 
    step3: # Mandate step
      title: 'Step3 Title'    
      roles:
        - CLIENT
        - LGIM
      title: 'Step4 Title'
      claimConfig:
        assigneeClaim: CLM-4

