workflowKey:
  title: 'Workflow Title'
  rules:
    enable: '!reqCancelIaaFma && !updSip' 
    visible: '!funding'  
  stepEnabledFor:
    - CLIENT
    - LGIM
    - ADVISORY
    - SPECIAL_ADVISORY
  steps:
    step1: # form step & also the initial step of the workflow
      title: 'Step1 Title'    
      rules:
        enable: 'TRUE'      
      stepEnabledFor:
        - CLIENT
        - LGIM
      claimConfig:
        assigneeClaim: CLM-1
      initialDataConfig: # Where initial data of the workflow coming from. Can refer scheme data or can refer workflow data 
        - key: assetValue
          source: scheme
          alias: assetValueAlias
        - key: 'fundValue'
          source: scheme
          alias: fundValueAlias          
        - key: returnTargetValue
          source: workflow
          workflow: workflowKey
          stepKey: stepKey
          alias: returnTargetData                   
      stepActions:    
        - STEP_ACTION_UPDATE_WORKFLOW:
            stepFunction: 'stepFunctionName'
            notificationConfig:
              notificationCode: N-R-11
                data:
                  - key: PROPOSAL_NAME
                    path: 'dataset.formData.assets.proposalName'              
            auditTrail:
              auditTrailAction: ATA_REQUEST_INITIAL_PROPOSAL
                data:
                  - key: DOC
                    value: 'IAA Document'              
      preserve: true # 
        - from: 'tab.valueAbc'
          to: 'valueAbc'                                   
    step2: # Approve Reject step
      title: 'Step2 Title'
      rules:
        enable: 'step1'        
      stepEnabledFor:
        - LGIM
      showRejectedData: true        
      authConfig:
        approvalType:
          - LGIM
        approveCount: ALL
        rejectCount: ALL                       
      claimConfig:
        authClaim: CLM-2 
        assigneeClaim: CLM-3
      stepActions:  
        - STEP_ACTION_AUTHORIZE:
            notificationConfig:
              notificationCode: N-R-11
                data:
                  - key: PROPOSAL_NAME
                    path: 'dataset.formData.assets.proposalName'                
            auditTrail:
              auditTrailAction: ATA_REQUEST_INITIAL_PROPOSAL
                data:
                  - key: PROPOSAL_NAME
                    path: 'dataset.formData.assets.proposalName'                        
    step3: # Mandate step
      title: 'Step3 Title'
      rules:
        enable: 'step1 && step2'  
        disable: '!step2'            
      stepEnabledFor:
        - CLIENT
        - LGIM
      title: 'Step4 Title'
      claimConfig:
        assigneeClaim: CLM-4
      stepActions:  
        - STEP_ACTION_PROCEED_WORKFLOW:
            notificationConfig:
              notificationCode: N-R-20
                data:
                  - key: PROPOSAL_NAME
                    path: 'dataset.formData.assets.proposalName'              
            auditTrail:
              auditTrailAction: ATA_MANDATE_WORKFLOW
                data:
                  - key: PROPOSAL_NAME
                    path: 'dataset.formData.assets.proposalName'
versionUpgradeConfig:        
  requiredValues:
    - var1.abcd 
    - var2.abcd 
    - var3.abcd                                           