workflowKey:
  title: 'Workflow Title'
  rules:
    enable: '!reqCancelIaaFma && !updSip' 
    visible: '!funding'  
  workflowEnabledFor:
    - CLIENT
    - LGIM
    - ADVISORY
    - SPECIAL_ADVISORY
  steps:
    step1: # form step & also the initial step of the workflow
      title: 'Step1 Title'
      rules:
        enable: 'TRUE'           
      workflowEnabledFor:
        - CLIENT
        - LGIM
      claimConfig:
        assigneeClaim: CLM-1
      initialDataConfig: # Where initial data of the workflow coming from. Can refer scheme data or can refer workflow data 
        - key: 'assetValue'
          source: scheme
        - key: 'fundValue'
          source: scheme                    
      stepActions:    
        - STEP_ACTION_UPDATE_WORKFLOW:
            stepFunction: 'adhocDocGen'
            notificationConfig:
              notificationCode: N-R-11
            auditTrail:
              auditTrailAction: ATA_REQUEST_INITIAL_PROPOSAL
      preserve: true                             
    step2: # Approve Reject step
      title: 'Step2 Title'
      rules:
        enable: 'step1'      
      workflowEnabledFor:
        - LGIM
      authConfig:
        approvalType:
          - LGIM
        approveCount: ALL
        rejectCount: ALL                       
      claimConfig:
        authClaim: CLM-2 
        assigneeClaim: CLM-3
      stepActions:  
        - STEP_ACTION_AUTHORIZE:
            notificationConfig:
              notificationCode: N-R-11
            auditTrail:
              auditTrailAction: ATA_REQUEST_INITIAL_PROPOSAL         
    step3: # Mandate step
      title: 'Step3 Title'
      rules:
        enable: 'step1 && step2'  
        disable: '!step2'            
      workflowEnabledFor:
        - CLIENT
        - LGIM
      title: 'Step4 Title'
      claimConfig:
        assigneeClaim: CLM-4
      stepActions:  
        - STEP_ACTION_PROCEED_WORKFLOW:
            notificationConfig:
              notificationCode: N-R-20
            auditTrail:
              auditTrailAction: ATA_MANDATE_WORKFLOW
requiredValues:
  - var1.abcd 
  - var2.abcd 
  - var3.abcd                        