# The workflow will be updated depending on a set of rules defined by the developer as per the requirement.
# These rules are the conditions that define the behavior( a workflow/step being enabled, disbaled or visible) of a workflow. 
# An attribute in the rule is a condition which interprets a boolean and these attributes can be a state of a step, or some custom attribute(Eg:  whether a document is uploaded/published/approved) . 
# These attributes will be saved in the database(registry service - which acts as a global registry) and will be visible to all the workflows. 
# Once a workflow gets updated these attributes will be updated in the registry and will be checked against the logic written in the rules.


version: 1.00
updateAVC:
  title: 'Workflow Title'
  rules:
    enable: '!reqCancelIaaFma && !updSip' 
    visible: '!funding'
  workflowEnabledFor:
    - CLIENT
    - LGIM  
  steps:
    step1: # form step & also the initial step of the workflow
      title: 'Step1 Title'    
      rules:
        enable: 'TRUE' 
      stepEnabledFor:
        - CLIENT
        - LGIM
      claimConfig:
        assigneeClaim: CLM-1       
      preserve: true  # save step data when workflow get mandated         
    step2: # Approve Reject step
      title: 'Step2 Title'
      rules:
        enable: 'step1'               
      stepEnabledFor:
        - LGIM
      authConfig:
        approvalType:
          - LGIM
        approveCount: 2
        rejectCount: ALL                       
      claimConfig:
        authClaim: CLM-2 
        assigneeClaim: CLM-3 
    step3: # Mandate step
      title: 'Step3 Title'
      rules:
        enable: 'step1 && step2'  
        disable: '!step2'           
      stepEnabledFor:
        - LGIM
      title: 'Step4 Title'
      claimConfig:
        assigneeClaim: CLM-4

versionUpgradeConfig:        
  requiredValues:
    - var1.abcd 
    - var2.abcd 
    - var3.abcd 