updateAVC:
  title: 'Workflow Title'
  # 
  workflowEnabledFor:
    - CLIENT
    - LGIM  
  steps:
    step1: # form step & also the initial step of the workflow
      stepEnabledFor:
        - CLIENT
        - LGIM
      title: 'Step1 Title'
      claimConfig:
        assigneeClaim: CLM-1       
      preserve: true           
    step2: # Approve Reject step
      title: 'Step2 Title'
      stepEnabledFor:
        - LGIM
      authConfig:
        approvalType:
          - LGIM
        approveCount: 2
        rejectCount: ALL                       
      claimConfig:
        authClaim: CLM-2 
        assigneeClaim: CLM-3 
    step3: # Mandate step
      title: 'Step3 Title'    
      stepEnabledFor:
        - LGIM
      title: 'Step4 Title'
      claimConfig:
        assigneeClaim: CLM-4

