formDataStep2:
  initialDataConfig:
    - projectionPath: 'ActivatedSchemeDataset.amao.formData.investment.assets'
      alias: 'returnTargetFormData'
    - projectionPath: 'ActivatedSchemeDataset.amao.formData.investment.assets'
      alias: 'returnTargetFormData' 
  notificationConfig:
    stepAction:
      - code: N-R-11
        data:
          - key: PROPOSAL_NAME
            path: 'dataset.formData.assets.proposalName'
    stepAction:
      - code: N-R-11
        data:
          - key: PROPOSAL_NAME
            path: 'dataset.formData.assets.proposalName'     
  auditTrail:
    stepAction:
      - auditTrailAction: ATA_REQUEST_INITIAL_PROPOSAL
        data:
          - key: PROPOSAL_NAME
            path: 'dataset.formData.assets.proposalName'
    stepAction:
      - auditTrailAction: ATA_SAVE_INITIAL_PROPOSAL
        data:
          - key: PROPOSAL_NAME
            path: 'dataset.formData.assets.proposalName'    
approveRejectStep1:
  authConfig:
    approvalType:
      - LGIM
    approveCount: 3
    rejectCount: ALL
    approveClaim: CLM-11
  notificationConfig:
    stepAction:
      - code: N-R-11
        data:
          - key: PROPOSAL_NAME
            path: 'dataset.formData.assets.proposalName'
    stepAction:
      - code: N-R-11
        data:
          - key: PROPOSAL_NAME
            path: 'dataset.formData.assets.proposalName'     
  auditTrail:
    stepAction:
      - auditTrailAction: ATA_REQUEST_INITIAL_PROPOSAL
        data:
          - key: PROPOSAL_NAME
            path: 'dataset.formData.assets.proposalName'
    stepAction:
      - auditTrailAction: ATA_SAVE_INITIAL_PROPOSAL
        data:
          - key: PROPOSAL_NAME
            path: 'dataset.formData.assets.proposalName'
  assigneeClaim: CLM-12
  dataCopyConfig:
    next:
      cp:
        - section: formData
          from: reqip
          to: dowip
        - section: approvers
          from: reqip
          to: dowip             