shehan
  enable:
    - NOT isSpecialAdvisory AND publishIaa
    - OR isSpecialAdvisory
    - AND publishFma AND publishPmc && publishSip

Charith
  enable: reqIaa:ENABLED AND schemeName:enabled OR appFma:DISABLE

Gayashan
  enable:
    - ((NOT isSpecialAdvisory AND publishIaa) OR isSpecialAdvisory) AND ( publishFma AND publishPmc AND publishSip) #WANT TO IDENTIFY ()